name: Gitlab Runner Service
#on: [repository_dispatch,push]

on: [repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - name: Maximize Build Space
#        uses: edersonbrilhante/gitlab-runner-action@main
#        with:
 #         root-reserve-mb: 512
 #         swap-size-mb: 1024
  #        remove-dotnet: 'true'
   #       remove-android: 'true'
    #      remove-haskell: 'true'

      - name: clean docker prune
        run: docker system prune -f || true
      - name: clean docker rmi 
        run: docker rmi $(docker images -aq)    || true
      - name: clean docker volume
        run: docker volume prune -f  || true
      - name: Gitlab Runner
        uses: edersonbrilhante/gitlab-runner-action@main
        with:
          registration-token: "${{ secrets.TOKEN }}"
          docker-image: "docker:19.03.12"
          name: ${{ github.run_id }}
          tag-list: [ "${{ github.event.client_payload.job_id }}" , "docker" , "linux" ]
